name: Movie Build

on:
  push:
    branches:
      - main
jobs:
  build:
    name: checkout
    steps:
      - name: checking out code 
        uses: actions/checkout@v2
        
      - name: install trivy
        run: |
         #install trivy
         sudo apt-get install wget apt-transport-https gnupg lsb-release -y
         wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
         echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
         sudo apt-get update
         sudo apt-get install trivy -y
         #command to scan files
         trivy fs .
 
        

        



