name: Movie Build

on:
  push:
    branches:
      - main
jobs:
  build:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: checking out code 
        uses: actions/checkout@v2
        
      - name: install trivy
        run: |
         #install trivy
         sudo apt-get install wget apt-transport-https gnupg lsb-release -y
         wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
         echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
         sudo apt-get update
         sudo apt-get install trivy -y
         #command to scan files
         trivy fs .
      - name: Docker build and push
        run: |
            #run commands to build and push docker images
            docker build --build-arg TMDB_V3_API_KEY=0b8d1978bd0908e373d56fded6b1d86a -t netflix .
            docker tag netflix badejotobi/netflix:latest
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker push badejotobi/netflix:latest
        env:
            DOCKER_CLI_ACI: 1
 
        

        



